name: Alamid Complete System
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  alamid_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Libs
        run: pip install pyTelegramBotAPI

      - name: Run Scraper and Striker
        run: |
          python scraper.py
          python striker.py

      - name: Run Telegram Bot
        env:
          MS_APP_PASS: ${{ secrets.MS_APP_PASS }}
        run: |
          # فحص إذا كان الملف ينتهي بـ .py أو لا وتشغيله
          if [ -f "ALAMID_STRIKE_FORCE.py" ]; then
            python ALAMID_STRIKE_FORCE.py
          elif [ -f "ALAMID_STRIKE_FORCE" ]; then
            python ALAMID_STRIKE_FORCE
          else
            print "❌ لم يتم العثور على ملف البوت بأي صيغة!"
            exit 1
          fi
