name: Send Marketing Emails

on:
  workflow_dispatch: # يخليك تشغل الكود بيدك

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-policy: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Striker
        env:
          # ربط الأسماء اللي في السيكرتس بالكود
          MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
        run: python striker.py
