name: Run Striker Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-striker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: python scraper.py

      - name: Run Radar
        run: python radar.py

      - name: Run Striker
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        run: python striker.py
