name: ALAMID_2026_FINAL
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install pyTelegramBotAPI
      - name: Launch
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          MS_APP_PASS: ${{ secrets.MS_APP_PASS }}
        run: python ALAMID_STRIKE_FORCE
