name: Send Marketing Emails

on:
  workflow_dispatch: # للتشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Run Striker
        env:
          # نمرر المفاتيح من السيكرتس مباشرة للكود
          MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
        run: |
          # أمر التشغيل مع إظهار النتائج فوراً
          python -u striker.py
